### PR TITLE
fix(providers): always generate completion data after info load

### LINKED ISSUE #1165: Autocomplete feature not working
This is my env:
- Titanium CLI v6.1.1, 
- Titanium SDK v12.1.2.GA
- Alloy v2.0.2
- Titanium ext v1.1.0
- Windows x64 

In addition , I disable other ext that may promotes conflict like XML by redhat and other plugins that rely on TypeScript.
However autocompletion didn't work at all either for *.js files and the Titanium's *.xml file.

Android build and live view are just running perfectly, other ext functionalities like creating project are just fine.
Only Autocompletion that is not working.

Help?

### PR DESCRIPTION
**Pull request by ewanharris**
In the initial load of projects we do not have environment information data and therefore no SDK data to generate completions from. So once we have loaded that environment data generate completions data for all of the app projects we have loaded.

Closes #1165

### CODE REVIEW

File: src/providers/index.ts [hunk 1]
```diff
@@ -144,20 +144,10 @@ export async function generateCompletions (force = false, project: Project): Pro
 		}
 		const sdkPath = sdkInfo.path;
 		// Generate the completions
-		const [ alloy, sdk ] = await Promise.all([
+		await Promise.all([
 			completion.generateAlloyCompletions(force, CompletionsFormat),
 			completion.generateSDKCompletions(force, sdkVersion, sdkPath, CompletionsFormat)
 		]);
-		if (sdk || alloy) {
```
Comment (ewanharris) [inline src/providers/index.ts:151]: I realised this is pretty useless information to a developer so just removed the info message
